import os
import re

print("Compiling matrix.proto...")
os.system(
    "python -m grpc_tools.protoc "
    "-I=grpc_layer --python_out=grpc_layer --grpc_python_out=grpc_layer grpc_layer/matrix.proto"
)

# Fix absolute import generated by protoc
pb2_grpc_file = os.path.join("grpc_layer", "matrix_pb2_grpc.py")
if os.path.exists(pb2_grpc_file):
    with open(pb2_grpc_file, 'r') as f:
        content = f.read()
    
    content = re.sub(
        r'^import matrix_pb2 as matrix__pb2',
        r'from . import matrix_pb2 as matrix__pb2',
        content,
        flags=re.MULTILINE
    )
    
    with open(pb2_grpc_file, 'w') as f:
        f.write(content)
    print("Fixed imports in matrix_pb2_grpc.py")
else:
    print(f"Warning: {pb2_grpc_file} not found.")
